const ids = ['head', 'body', 'arms', 'legs', 'scaffold', 'ground'];
let result;
let guessedLetters = [];
document.addEventListener('DOMContentLoaded', function () {
    ids.forEach(id => {
        ChangeOpacity(id, 0);
    });
});

document.addEventListener('DOMContentLoaded', () => {

    const {word, hiddenWord} = GetRandomWord();
    document.getElementById("letterbox-container").innerHTML = GenerateLetterBoxes(hiddenWord);
    AskPlayer(word);
});
//TODO duplicate?
function GenerateLetterBoxes(hiddenWord) {
    {
        return hiddenWord.map(letter => `<div class="letter-box">${letter}</div>`).join('');
    }
}

function FillInLetterBoxes(letter, wordLength) {
    let letterBoxes = Array(wordLength.length).fill('');
    for (let i = 0; i < wordLength.length; i++) {

        if (letter[i] === wordLength[i])
        {
            letterBoxes.push(`<div class="letter-box">${letter[i]}</div>`);
        }
        else
        {
            letterBoxes.push(`<div class="letter-box"></div>`);
        }



    }
    return letterBoxes.join('');
}

function ChangeOpacity(id, newOpacity) {
    let svgDocument = document.querySelector("#hangman-game").contentWindow.document;
    let element = svgDocument.getElementById(id);

    if (element) {
        element.setAttribute('opacity', newOpacity);
    }
}

function GetRandomWord() {
    const fooWords = ["monitor", "program", "application", "keyboard", "javascript", "autogenerated", "network"];
    const randomIndex = Math.floor(Math.random() * fooWords.length);
    const word = fooWords[randomIndex];
    const hiddenWord = MakeWordHidden(word);
    return {word, hiddenWord};

}

function MakeWordHidden(word) {
    return Array(word.length).fill(' ');
}

function AskPlayer(word) {
    const userInputForm = document.querySelector('.input-field-form');
    const userInput = document.querySelector("input[name='user-input']");
    userInput.addEventListener('input', function () {
        result = this.value;
    });
    userInputForm.addEventListener('submit', function (e) {
        e.preventDefault();
        result = result ? result.toLowerCase().trim() : '';
        RevealWord(result, word);

    });

    return result;
}

function RevealWord(guess, word) {

    if (guess.match(word)) {
        let guessArray = [...guess];
       document.getElementById("letterbox-container").innerHTML = FillInLetterBoxes(guessArray, word);
    }
    for (let i = 0; i < word.length; i++) {
        if (guess === word[i]) {
            guessedLetters[i] = guess
            document.getElementById("letterbox-container").innerHTML = FillInLetterBoxes(guessedLetters, word);

        }
    }
}